/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package note_quiz;
/**
 *
 * @author mashit
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSelectNote = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();
        lbl6A = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbl6Gs = new javax.swing.JLabel();
        lbl6G = new javax.swing.JLabel();
        lbl6Fs = new javax.swing.JLabel();
        lbl6As = new javax.swing.JLabel();
        lbl6F = new javax.swing.JLabel();
        lbl6B = new javax.swing.JLabel();
        lbl6C = new javax.swing.JLabel();
        lbl6Cs = new javax.swing.JLabel();
        lbl6D = new javax.swing.JLabel();
        lbl6Ds = new javax.swing.JLabel();
        lbl6E = new javax.swing.JLabel();
        lbl5D = new javax.swing.JLabel();
        lbl5Cs = new javax.swing.JLabel();
        lbl5C = new javax.swing.JLabel();
        lbl5B = new javax.swing.JLabel();
        lbl5Ds = new javax.swing.JLabel();
        lbl5As = new javax.swing.JLabel();
        lbl5E = new javax.swing.JLabel();
        lbl5F = new javax.swing.JLabel();
        lbl5Fs = new javax.swing.JLabel();
        lbl5G = new javax.swing.JLabel();
        lbl5Gs = new javax.swing.JLabel();
        lbl5A = new javax.swing.JLabel();
        lbl4G = new javax.swing.JLabel();
        lbl4Fs = new javax.swing.JLabel();
        lbl4F = new javax.swing.JLabel();
        lbl4E = new javax.swing.JLabel();
        lbl4Gs = new javax.swing.JLabel();
        lbl4Ds = new javax.swing.JLabel();
        lbl4A = new javax.swing.JLabel();
        lbl4As = new javax.swing.JLabel();
        lbl4B = new javax.swing.JLabel();
        lbl4C = new javax.swing.JLabel();
        lbl4Cs = new javax.swing.JLabel();
        lbl4D = new javax.swing.JLabel();
        lbl3C = new javax.swing.JLabel();
        lbl3B = new javax.swing.JLabel();
        lbl3As = new javax.swing.JLabel();
        lbl3A = new javax.swing.JLabel();
        lbl3Cs = new javax.swing.JLabel();
        lbl3Gs = new javax.swing.JLabel();
        lbl3D = new javax.swing.JLabel();
        lbl3Ds = new javax.swing.JLabel();
        lbl3E = new javax.swing.JLabel();
        lbl3F = new javax.swing.JLabel();
        lbl3Fs = new javax.swing.JLabel();
        lbl3G = new javax.swing.JLabel();
        lbl2E = new javax.swing.JLabel();
        lbl2Ds = new javax.swing.JLabel();
        lbl2D = new javax.swing.JLabel();
        lbl2Cs = new javax.swing.JLabel();
        lbl2F = new javax.swing.JLabel();
        lbl2C = new javax.swing.JLabel();
        lbl2Fs = new javax.swing.JLabel();
        lbl2G = new javax.swing.JLabel();
        lbl2Gs = new javax.swing.JLabel();
        lbl2A = new javax.swing.JLabel();
        lbl2As = new javax.swing.JLabel();
        lbl2B = new javax.swing.JLabel();
        lbl1A = new javax.swing.JLabel();
        lbl1Gs = new javax.swing.JLabel();
        lbl1G = new javax.swing.JLabel();
        lbl1Fs = new javax.swing.JLabel();
        lbl1As = new javax.swing.JLabel();
        lbl1F = new javax.swing.JLabel();
        lbl1B = new javax.swing.JLabel();
        lbl1C = new javax.swing.JLabel();
        lbl1Cs = new javax.swing.JLabel();
        lbl1D = new javax.swing.JLabel();
        lbl1Ds = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        lblFretBoard = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(null);

        lblSelectNote.setText("Select the notes: ");
        getContentPane().add(lblSelectNote);
        lblSelectNote.setBounds(10, 190, 126, 15);

        lblNote.setText("jLabel3");
        getContentPane().add(lblNote);
        lblNote.setBounds(140, 190, 51, 15);

        lbl6A.setText("X");
        getContentPane().add(lbl6A);
        lbl6A.setBounds(185, 116, 10, 15);
        lbl6A.getAccessibleContext().setAccessibleName("F");
        lbl6A.getAccessibleContext().setAccessibleDescription("");

        jButton1.setText("Start");
        jButton1.setActionCommand("btnStart");
        jButton1.setName("btnStart"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 190, 70, 25);

        lbl6Gs.setText("X");
        getContentPane().add(lbl6Gs);
        lbl6Gs.setBounds(152, 116, 10, 15);

        lbl6G.setText("X");
        getContentPane().add(lbl6G);
        lbl6G.setBounds(118, 116, 10, 15);

        lbl6Fs.setText("X");
        getContentPane().add(lbl6Fs);
        lbl6Fs.setBounds(84, 116, 10, 15);

        lbl6As.setText("X");
        getContentPane().add(lbl6As);
        lbl6As.setBounds(219, 116, 10, 15);

        lbl6F.setText("X");
        getContentPane().add(lbl6F);
        lbl6F.setBounds(50, 116, 10, 15);

        lbl6B.setText("X");
        getContentPane().add(lbl6B);
        lbl6B.setBounds(252, 116, 10, 15);

        lbl6C.setText("X");
        getContentPane().add(lbl6C);
        lbl6C.setBounds(286, 116, 10, 15);

        lbl6Cs.setText("X");
        getContentPane().add(lbl6Cs);
        lbl6Cs.setBounds(320, 116, 10, 15);

        lbl6D.setText("X");
        getContentPane().add(lbl6D);
        lbl6D.setBounds(353, 116, 10, 15);

        lbl6Ds.setText("X");
        getContentPane().add(lbl6Ds);
        lbl6Ds.setBounds(387, 116, 10, 15);

        lbl6E.setText("X");
        getContentPane().add(lbl6E);
        lbl6E.setBounds(420, 116, 10, 15);

        lbl5D.setText("X");
        getContentPane().add(lbl5D);
        lbl5D.setBounds(185, 93, 10, 15);

        lbl5Cs.setText("X");
        getContentPane().add(lbl5Cs);
        lbl5Cs.setBounds(152, 93, 10, 15);

        lbl5C.setText("X");
        getContentPane().add(lbl5C);
        lbl5C.setBounds(118, 93, 10, 15);

        lbl5B.setText("X");
        getContentPane().add(lbl5B);
        lbl5B.setBounds(84, 93, 10, 15);

        lbl5Ds.setText("X");
        getContentPane().add(lbl5Ds);
        lbl5Ds.setBounds(219, 93, 10, 15);

        lbl5As.setText("X");
        getContentPane().add(lbl5As);
        lbl5As.setBounds(50, 93, 10, 15);

        lbl5E.setText("X");
        getContentPane().add(lbl5E);
        lbl5E.setBounds(252, 93, 10, 15);

        lbl5F.setText("X");
        getContentPane().add(lbl5F);
        lbl5F.setBounds(286, 93, 10, 15);

        lbl5Fs.setText("X");
        getContentPane().add(lbl5Fs);
        lbl5Fs.setBounds(320, 93, 10, 15);

        lbl5G.setText("X");
        getContentPane().add(lbl5G);
        lbl5G.setBounds(353, 93, 10, 15);

        lbl5Gs.setText("X");
        getContentPane().add(lbl5Gs);
        lbl5Gs.setBounds(387, 93, 10, 15);

        lbl5A.setText("X");
        getContentPane().add(lbl5A);
        lbl5A.setBounds(420, 93, 10, 15);

        lbl4G.setText("X");
        getContentPane().add(lbl4G);
        lbl4G.setBounds(185, 72, 10, 15);

        lbl4Fs.setText("X");
        getContentPane().add(lbl4Fs);
        lbl4Fs.setBounds(152, 72, 10, 15);

        lbl4F.setText("X");
        getContentPane().add(lbl4F);
        lbl4F.setBounds(118, 72, 10, 15);

        lbl4E.setText("X");
        getContentPane().add(lbl4E);
        lbl4E.setBounds(84, 72, 10, 15);

        lbl4Gs.setText("X");
        getContentPane().add(lbl4Gs);
        lbl4Gs.setBounds(219, 72, 10, 15);

        lbl4Ds.setText("X");
        getContentPane().add(lbl4Ds);
        lbl4Ds.setBounds(50, 72, 10, 15);

        lbl4A.setText("X");
        getContentPane().add(lbl4A);
        lbl4A.setBounds(252, 72, 10, 15);

        lbl4As.setText("X");
        getContentPane().add(lbl4As);
        lbl4As.setBounds(286, 72, 10, 15);

        lbl4B.setText("X");
        getContentPane().add(lbl4B);
        lbl4B.setBounds(320, 72, 10, 15);

        lbl4C.setText("X");
        getContentPane().add(lbl4C);
        lbl4C.setBounds(353, 72, 10, 15);

        lbl4Cs.setText("X");
        getContentPane().add(lbl4Cs);
        lbl4Cs.setBounds(387, 72, 10, 15);

        lbl4D.setText("X");
        getContentPane().add(lbl4D);
        lbl4D.setBounds(420, 72, 10, 15);

        lbl3C.setText("X");
        getContentPane().add(lbl3C);
        lbl3C.setBounds(185, 50, 10, 15);

        lbl3B.setText("X");
        getContentPane().add(lbl3B);
        lbl3B.setBounds(152, 50, 10, 15);

        lbl3As.setText("X");
        getContentPane().add(lbl3As);
        lbl3As.setBounds(118, 50, 10, 15);

        lbl3A.setText("X");
        getContentPane().add(lbl3A);
        lbl3A.setBounds(84, 50, 10, 15);

        lbl3Cs.setText("X");
        getContentPane().add(lbl3Cs);
        lbl3Cs.setBounds(219, 50, 10, 15);

        lbl3Gs.setText("X");
        getContentPane().add(lbl3Gs);
        lbl3Gs.setBounds(50, 50, 10, 15);

        lbl3D.setText("X");
        getContentPane().add(lbl3D);
        lbl3D.setBounds(252, 50, 10, 15);

        lbl3Ds.setText("X");
        getContentPane().add(lbl3Ds);
        lbl3Ds.setBounds(286, 50, 10, 15);

        lbl3E.setText("X");
        getContentPane().add(lbl3E);
        lbl3E.setBounds(320, 50, 10, 15);

        lbl3F.setText("X");
        getContentPane().add(lbl3F);
        lbl3F.setBounds(353, 50, 10, 15);

        lbl3Fs.setText("X");
        getContentPane().add(lbl3Fs);
        lbl3Fs.setBounds(387, 50, 10, 15);

        lbl3G.setText("X");
        getContentPane().add(lbl3G);
        lbl3G.setBounds(420, 50, 10, 15);

        lbl2E.setText("X");
        getContentPane().add(lbl2E);
        lbl2E.setBounds(185, 27, 10, 15);

        lbl2Ds.setText("X");
        getContentPane().add(lbl2Ds);
        lbl2Ds.setBounds(152, 27, 10, 15);

        lbl2D.setText("X");
        getContentPane().add(lbl2D);
        lbl2D.setBounds(118, 27, 10, 15);

        lbl2Cs.setText("X");
        getContentPane().add(lbl2Cs);
        lbl2Cs.setBounds(84, 27, 10, 15);

        lbl2F.setText("X");
        getContentPane().add(lbl2F);
        lbl2F.setBounds(219, 27, 10, 15);

        lbl2C.setText("X");
        getContentPane().add(lbl2C);
        lbl2C.setBounds(50, 27, 10, 15);

        lbl2Fs.setText("X");
        getContentPane().add(lbl2Fs);
        lbl2Fs.setBounds(252, 27, 10, 15);

        lbl2G.setText("X");
        getContentPane().add(lbl2G);
        lbl2G.setBounds(286, 27, 10, 15);

        lbl2Gs.setText("X");
        getContentPane().add(lbl2Gs);
        lbl2Gs.setBounds(320, 27, 10, 15);

        lbl2A.setText("X");
        getContentPane().add(lbl2A);
        lbl2A.setBounds(353, 27, 10, 15);

        lbl2As.setText("X");
        getContentPane().add(lbl2As);
        lbl2As.setBounds(387, 27, 10, 15);

        lbl2B.setText("X");
        getContentPane().add(lbl2B);
        lbl2B.setBounds(420, 27, 10, 15);

        lbl1A.setText("X");
        getContentPane().add(lbl1A);
        lbl1A.setBounds(185, 5, 10, 15);

        lbl1Gs.setText("X");
        getContentPane().add(lbl1Gs);
        lbl1Gs.setBounds(152, 5, 10, 15);

        lbl1G.setText("X");
        getContentPane().add(lbl1G);
        lbl1G.setBounds(118, 5, 10, 15);

        lbl1Fs.setText("X");
        getContentPane().add(lbl1Fs);
        lbl1Fs.setBounds(84, 5, 10, 15);

        lbl1As.setText("X");
        getContentPane().add(lbl1As);
        lbl1As.setBounds(219, 5, 10, 15);

        lbl1F.setText("X");
        getContentPane().add(lbl1F);
        lbl1F.setBounds(50, 5, 10, 15);

        lbl1B.setText("X");
        getContentPane().add(lbl1B);
        lbl1B.setBounds(252, 5, 10, 15);

        lbl1C.setText("X");
        getContentPane().add(lbl1C);
        lbl1C.setBounds(286, 5, 10, 15);

        lbl1Cs.setText("X");
        getContentPane().add(lbl1Cs);
        lbl1Cs.setBounds(320, 5, 10, 15);

        lbl1D.setText("X");
        getContentPane().add(lbl1D);
        lbl1D.setBounds(353, 5, 10, 15);

        lbl1Ds.setText("X");
        getContentPane().add(lbl1Ds);
        lbl1Ds.setBounds(387, 5, 10, 15);

        jLabel39.setText("X");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(420, 5, 10, 15);

        lblFretBoard.setIcon(new javax.swing.ImageIcon("/media/FreeAgent GoFlex Drive/Adv Java/NoteQuiz/JavaFXSwingApplication2/Images/fret_Board.gif")); // NOI18N
        lblFretBoard.setText("jLabel1");
        getContentPane().add(lblFretBoard);
        lblFretBoard.setBounds(0, 0, 442, 148);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String[] notes = {"A","A#","B","C","C#","D","D#","E","F","F#","G","G#"};
        
                        
       
        lblNote.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbl1A;
    private javax.swing.JLabel lbl1As;
    private javax.swing.JLabel lbl1B;
    private javax.swing.JLabel lbl1C;
    private javax.swing.JLabel lbl1Cs;
    private javax.swing.JLabel lbl1D;
    private javax.swing.JLabel lbl1Ds;
    private javax.swing.JLabel lbl1F;
    private javax.swing.JLabel lbl1Fs;
    private javax.swing.JLabel lbl1G;
    private javax.swing.JLabel lbl1Gs;
    private javax.swing.JLabel lbl2A;
    private javax.swing.JLabel lbl2As;
    private javax.swing.JLabel lbl2B;
    private javax.swing.JLabel lbl2C;
    private javax.swing.JLabel lbl2Cs;
    private javax.swing.JLabel lbl2D;
    private javax.swing.JLabel lbl2Ds;
    private javax.swing.JLabel lbl2E;
    private javax.swing.JLabel lbl2F;
    private javax.swing.JLabel lbl2Fs;
    private javax.swing.JLabel lbl2G;
    private javax.swing.JLabel lbl2Gs;
    private javax.swing.JLabel lbl3A;
    private javax.swing.JLabel lbl3As;
    private javax.swing.JLabel lbl3B;
    private javax.swing.JLabel lbl3C;
    private javax.swing.JLabel lbl3Cs;
    private javax.swing.JLabel lbl3D;
    private javax.swing.JLabel lbl3Ds;
    private javax.swing.JLabel lbl3E;
    private javax.swing.JLabel lbl3F;
    private javax.swing.JLabel lbl3Fs;
    private javax.swing.JLabel lbl3G;
    private javax.swing.JLabel lbl3Gs;
    private javax.swing.JLabel lbl4A;
    private javax.swing.JLabel lbl4As;
    private javax.swing.JLabel lbl4B;
    private javax.swing.JLabel lbl4C;
    private javax.swing.JLabel lbl4Cs;
    private javax.swing.JLabel lbl4D;
    private javax.swing.JLabel lbl4Ds;
    private javax.swing.JLabel lbl4E;
    private javax.swing.JLabel lbl4F;
    private javax.swing.JLabel lbl4Fs;
    private javax.swing.JLabel lbl4G;
    private javax.swing.JLabel lbl4Gs;
    private javax.swing.JLabel lbl5A;
    private javax.swing.JLabel lbl5As;
    private javax.swing.JLabel lbl5B;
    private javax.swing.JLabel lbl5C;
    private javax.swing.JLabel lbl5Cs;
    private javax.swing.JLabel lbl5D;
    private javax.swing.JLabel lbl5Ds;
    private javax.swing.JLabel lbl5E;
    private javax.swing.JLabel lbl5F;
    private javax.swing.JLabel lbl5Fs;
    private javax.swing.JLabel lbl5G;
    private javax.swing.JLabel lbl5Gs;
    private javax.swing.JLabel lbl6A;
    private javax.swing.JLabel lbl6As;
    private javax.swing.JLabel lbl6B;
    private javax.swing.JLabel lbl6C;
    private javax.swing.JLabel lbl6Cs;
    private javax.swing.JLabel lbl6D;
    private javax.swing.JLabel lbl6Ds;
    private javax.swing.JLabel lbl6E;
    private javax.swing.JLabel lbl6F;
    private javax.swing.JLabel lbl6Fs;
    private javax.swing.JLabel lbl6G;
    private javax.swing.JLabel lbl6Gs;
    private javax.swing.JLabel lblFretBoard;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblSelectNote;
    // End of variables declaration//GEN-END:variables
}
